trigger: none

pr:
- master

###################
### Android BUILD
###################
jobs:

- job: Android_Job
  displayName: Xamarin Forms Android CI Build

  pool:
    vmImage: 'windows-2019'

  steps:
  - task: NuGetCommand@2
    displayName: "Restore NuGet packages"
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
    
  - task: XamarinAndroid@1
    inputs:
      projectFile: '**/MyIncredibleApp.Android.csproj'
      createAppPackage: false
      msbuildVersionOption: 'latest'
      jdkOption: 'JDKVersion'
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**\*Tests.dll'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      runInParallel: true